language: node_js
node_js:
  - "5.10"

before_install:
  - "export CHROME_BIN=/usr/bin/google-chrome"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - npm install

script:
  - gulp build
  - gulp test --coverage
  - gulp docs
  - gulp package
  - gulp bower

notifications:
  slack: chartjs:pcfCZR6ugg5TEcaLtmIfQYuA

sudo: required
dist: trusty

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


# IMPORTANT: scripts require GITHUB_AUTH_TOKEN and GITHUB_AUTH_EMAIL environment variables
# IMPORTANT: scripts has to be set executables in the Git repository (error 127)
# https://github.com/travis-ci/travis-ci/issues/5538#issuecomment-225025939

deploy:
- provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
